name: Pull Request

on:
  pull_request:

jobs:
  go:
    name: Validate Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate and test Go code
        id: go
        uses: ./.github/actions/go
        with:
          COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD }}
